import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/myComponents/Navigation/Navigation";
import MobileNavigation from "@/components/myComponents/Navigation/MobileNavigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen w-screen bg-slate-300">
          <div className="z-50 block sm:hidden fixed bottom-4 left-4 bg-slate-400 ">
            <MobileNavigation />
          </div>
          <div className="flex h-full w-full ">
            <div className="bg-slate-800  text-white hidden sm:block sm:w-64 overflow-y-auto">
              <Navigation />
            </div>
            <div className="bg-slate-300 flex-1 overflow-y-auto">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
